import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CatalogLayout } from "@/components/catalog/catalog-layout";
import { parseCatalogFilters, type RawSearchParams } from "@/lib/catalog/filters";
import { getCatalogPageData, getPublicCategoryBySlug } from "@/lib/supabase/public-queries";
import { catalogMetadataPolicy, createNotFoundMetadata, createPageMetadata } from "@/lib/seo/metadata";
type Props = { params: Promise<{ category: string }>; searchParams: Promise<RawSearchParams> };
export async function generateMetadata({ params, searchParams }: Props): Promise<Metadata> { const [{ category }, query] = await Promise.all([params, searchParams]); const item = await getPublicCategoryBySlug(category); if (!item) return createNotFoundMetadata(); const filters = parseCatalogFilters(query); const catalog = await getCatalogPageData(filters, undefined, category); const basePath = `/motorcycles/category/${category}`; const policy = catalogMetadataPolicy(query, basePath); const invalidPage = filters.page > catalog.totalPages; return createPageMetadata({ title: item.seoTitle ?? `${item.name} Motorcycles`, description: item.seoDescription ?? `Explore ${item.name.toLowerCase()} at OW Motors.`, path: invalidPage ? basePath : policy.canonicalPath, noIndex: policy.noIndex || invalidPage || catalog.total === 0, absoluteTitle: Boolean(item.seoTitle) }); }
export default async function CategoryPage({ params, searchParams }: Props) { const { category } = await params; const item = await getPublicCategoryBySlug(category); if (!item) notFound(); const filters = parseCatalogFilters(await searchParams); const catalog = await getCatalogPageData(filters, undefined, category); const path = `/motorcycles/category/${category}`; return <CatalogLayout title={item.name} description={item.description} pathname={path} filters={filters} catalog={catalog} lockedCategory={category} breadcrumbs={[{ label: "Home", href: "/" }, { label: "Motorcycles", href: "/motorcycles" }, { label: item.name }]} />; }
