import { AdminForm } from "@/components/admin/admin-form.client";
import { adminInputClass, adminLabelClass, adminTextareaClass } from "@/components/admin/admin-ui";
import { deleteFeature, saveFeature } from "@/app/admin/inventory-actions";
import type { Tables } from "@/lib/supabase/database.types";

function FeatureForm({ motorcycleId, feature, isAdmin }: Readonly<{ motorcycleId: string; feature?: Tables<"motorcycle_features">; isAdmin: boolean }>) {
  return <div className="space-y-5"><AdminForm action={saveFeature} submitLabel={feature ? "Update feature" : "Add feature"}><input type="hidden" name="motorcycleId" value={motorcycleId} />{feature ? <input type="hidden" name="id" value={feature.id} /> : null}<div className="grid gap-4 sm:grid-cols-2"><label className={adminLabelClass}>Group<input className={adminInputClass} name="groupName" required minLength={2} maxLength={100} defaultValue={feature?.group_name ?? "Performance"} /></label><label className={adminLabelClass}>Title<input className={adminInputClass} name="title" required minLength={2} maxLength={140} defaultValue={feature?.title} /></label></div><label className={adminLabelClass}>Description<textarea className={adminTextareaClass} name="description" required minLength={10} maxLength={1000} rows={4} defaultValue={feature?.description} /></label><div className="grid gap-4 sm:grid-cols-2"><label className={adminLabelClass}>Icon identifier<input className={adminInputClass} name="iconIdentifier" pattern="[a-z0-9]+(-[a-z0-9]+)*" defaultValue={feature?.icon_identifier ?? ""} placeholder="shield" /></label><label className={adminLabelClass}>Sort order<input className={adminInputClass} name="sortOrder" type="number" min={0} required defaultValue={feature?.sort_order ?? 0} /></label></div></AdminForm>{feature && isAdmin ? <AdminForm action={deleteFeature} submitLabel="Delete feature" pendingLabel="Deleting…" destructive confirmMessage={`Delete ${feature.title}?`} className="border-t border-border pt-5"><input type="hidden" name="id" value={feature.id} /><input type="hidden" name="motorcycleId" value={motorcycleId} /></AdminForm> : null}</div>;
}

export function FeatureManager({ motorcycleId, features, isAdmin }: Readonly<{ motorcycleId: string; features: readonly Tables<"motorcycle_features">[]; isAdmin: boolean }>) {
  return <div className="space-y-6"><div className="border border-border bg-soft-gray p-5"><h3 className="font-display text-xl font-bold">Add feature</h3><div className="mt-5"><FeatureForm motorcycleId={motorcycleId} isAdmin={isAdmin} /></div></div>{features.map((feature) => <details key={feature.id} className="group border border-border"><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between gap-4 px-4 [&::-webkit-details-marker]:hidden"><span><strong>{feature.title}</strong><span className="ml-3 text-xs text-cool-gray">{feature.group_name}</span></span><span aria-hidden="true" className="group-open:rotate-45">＋</span></summary><div className="border-t border-border p-5"><FeatureForm motorcycleId={motorcycleId} feature={feature} isAdmin={isAdmin} /></div></details>)}</div>;
}
