import Image from "next/image";
import { AdminForm } from "@/components/admin/admin-form.client";
import { adminInputClass, adminLabelClass } from "@/components/admin/admin-ui";
import { deleteMotorcycleImage, updateMotorcycleImage, uploadMotorcycleImage } from "@/app/admin/inventory-actions";
import { motorcycleStoragePublicUrl } from "@/lib/supabase/storage";
import type { Tables } from "@/lib/supabase/database.types";

const imageTypes = ["gallery", "hero", "thumbnail", "color", "overview", "open_graph"] as const;

function VariantSelect({ variants, defaultValue }: Readonly<{ variants: readonly Tables<"motorcycle_variants">[]; defaultValue?: string | null }>) { return <select className={adminInputClass} name="variantId" defaultValue={defaultValue ?? ""}><option value="">All variants</option>{variants.map((variant) => <option key={variant.id} value={variant.id}>{variant.cc}cc — {variant.color_name}</option>)}</select>; }

export function ImageManager({ motorcycleId, images, variants, isAdmin }: Readonly<{ motorcycleId: string; images: readonly Tables<"motorcycle_images">[]; variants: readonly Tables<"motorcycle_variants">[]; isAdmin: boolean }>) {
  return <div className="space-y-6"><div className="border border-border bg-soft-gray p-5"><h3 className="font-display text-xl font-bold">Upload image</h3><p className="mt-1 text-xs text-cool-gray">JPEG, PNG, WebP, or AVIF. Maximum 900 KB. Use descriptive alt text.</p><div className="mt-5"><AdminForm action={uploadMotorcycleImage} submitLabel="Upload image" pendingLabel="Uploading…"><input type="hidden" name="motorcycleId" value={motorcycleId} /><div className="grid gap-4 sm:grid-cols-2"><label className={adminLabelClass}>Image file<input className={`${adminInputClass} py-2`} name="file" type="file" accept="image/jpeg,image/png,image/webp,image/avif" required /></label><label className={adminLabelClass}>Variant<VariantSelect variants={variants} /></label></div><label className={adminLabelClass}>Alt text<input className={adminInputClass} name="altText" required minLength={3} maxLength={240} /></label><div className="grid gap-4 sm:grid-cols-2"><label className={adminLabelClass}>Image type<select className={adminInputClass} name="imageType" defaultValue="gallery">{imageTypes.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label><label className={adminLabelClass}>Sort order<input className={adminInputClass} name="sortOrder" type="number" min={0} required defaultValue={0} /></label></div><label className="flex min-h-11 items-center gap-3 text-sm font-semibold"><input type="checkbox" name="isPrimary" className="h-4 w-4 accent-brand" /> Primary image</label></AdminForm></div></div>
    {images.length ? <div className="grid gap-5 xl:grid-cols-2">{images.map((image) => <article key={image.id} className="border border-border"><div className="relative aspect-[16/9] bg-soft-gray"><Image src={motorcycleStoragePublicUrl(image.storage_path)} alt={image.alt_text} fill sizes="(min-width:1280px) 40vw, 90vw" className="object-contain p-3" /></div><div className="p-5"><AdminForm action={updateMotorcycleImage} submitLabel="Update image"><input type="hidden" name="id" value={image.id} /><input type="hidden" name="motorcycleId" value={motorcycleId} /><label className={adminLabelClass}>Variant<VariantSelect variants={variants} defaultValue={image.variant_id} /></label><label className={adminLabelClass}>Alt text<input className={adminInputClass} name="altText" required defaultValue={image.alt_text} /></label><div className="grid gap-4 sm:grid-cols-2"><label className={adminLabelClass}>Type<select className={adminInputClass} name="imageType" defaultValue={image.image_type}>{imageTypes.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label><label className={adminLabelClass}>Sort order<input className={adminInputClass} name="sortOrder" type="number" min={0} required defaultValue={image.sort_order} /></label></div><label className="flex min-h-11 items-center gap-3 text-sm font-semibold"><input type="checkbox" name="isPrimary" defaultChecked={image.is_primary} className="h-4 w-4 accent-brand" /> Primary image</label></AdminForm>{isAdmin ? <AdminForm action={deleteMotorcycleImage} submitLabel="Delete image" pendingLabel="Deleting…" destructive confirmMessage="Delete this image record and Storage object?" className="mt-5 border-t border-border pt-5"><input type="hidden" name="id" value={image.id} /><input type="hidden" name="motorcycleId" value={motorcycleId} /></AdminForm> : null}</div></article>)}</div> : <p className="text-sm text-cool-gray">No images uploaded yet.</p>}
  </div>;
}
