import { AdminForm } from "@/components/admin/admin-form.client";
import { adminInputClass, adminLabelClass, adminTextareaClass, StatusBadge } from "@/components/admin/admin-ui";
import { deleteMotorcycle, updateMotorcyclePublishing, updateMotorcycleSeo } from "@/app/admin/motorcycle-actions";
import type { Tables } from "@/lib/supabase/database.types";

export function MotorcycleSeoForm({ motorcycle }: Readonly<{ motorcycle: Tables<"motorcycles"> }>) {
  return <AdminForm action={updateMotorcycleSeo} submitLabel="Update SEO metadata"><input type="hidden" name="id" value={motorcycle.id} /><label className={adminLabelClass}>SEO title<input className={adminInputClass} name="seoTitle" minLength={10} maxLength={70} defaultValue={motorcycle.seo_title ?? ""} /><span className="mt-1 block text-[10px] normal-case tracking-normal text-cool-gray">10–70 characters. Leave blank to use the product name.</span></label><label className={adminLabelClass}>SEO description<textarea className={adminTextareaClass} name="seoDescription" minLength={50} maxLength={180} rows={4} defaultValue={motorcycle.seo_description ?? ""} /><span className="mt-1 block text-[10px] normal-case tracking-normal text-cool-gray">50–180 characters. Leave blank to use the short description.</span></label></AdminForm>;
}

export function MotorcyclePublishingForm({ motorcycle, activeDefaultVariant, imageCount, isAdmin }: Readonly<{ motorcycle: Tables<"motorcycles">; activeDefaultVariant: boolean; imageCount: number; isAdmin: boolean }>) {
  return <div className="space-y-7"><div className="grid gap-3 sm:grid-cols-3"><div className="border border-border p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-cool-gray">Current status</p><div className="mt-3"><StatusBadge value={motorcycle.publication_status} /></div></div><div className="border border-border p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-cool-gray">Active default variant</p><p className={`mt-3 text-sm font-semibold ${activeDefaultVariant ? "text-emerald-700" : "text-brand"}`}>{activeDefaultVariant ? "Ready" : "Required"}</p></div><div className="border border-border p-4"><p className="text-[10px] font-bold uppercase tracking-widest text-cool-gray">Images</p><p className={`mt-3 text-sm font-semibold ${imageCount ? "text-emerald-700" : "text-brand"}`}>{imageCount ? `${imageCount} uploaded` : "At least one required"}</p></div></div>
    <AdminForm action={updateMotorcyclePublishing} submitLabel="Update publication status" confirmMessage={motorcycle.publication_status === "published" ? "Change this published motorcycle's status?" : undefined}><input type="hidden" name="id" value={motorcycle.id} /><label className={adminLabelClass}>Publication status<select className={adminInputClass} name="publicationStatus" defaultValue={motorcycle.publication_status}><option value="draft">Draft — staff only</option><option value="published">Published — publicly visible</option><option value="archived">Archived — staff only</option></select></label><p className="text-xs leading-5 text-cool-gray">Publishing is blocked until an active default variant and at least one image exist. Public RLS policies expose only published motorcycles and active variants.</p></AdminForm>
    {isAdmin ? <div className="border-t border-border pt-7"><h3 className="font-display text-xl font-bold text-brand">Danger zone</h3><p className="mt-2 text-xs text-cool-gray">Deletion is permanent and may be blocked while variants, images, specifications, features, or customer requests reference this motorcycle.</p><div className="mt-5"><AdminForm action={deleteMotorcycle} submitLabel="Delete motorcycle" pendingLabel="Deleting…" destructive confirmMessage={`Permanently delete ${motorcycle.name}?`}><input type="hidden" name="id" value={motorcycle.id} /></AdminForm></div></div> : null}
  </div>;
}
