import { AdminForm } from "@/components/admin/admin-form.client";
import { adminInputClass, adminLabelClass, StatusBadge } from "@/components/admin/admin-ui";
import { deleteVariant, saveVariant } from "@/app/admin/inventory-actions";
import type { Tables } from "@/lib/supabase/database.types";

function VariantForm({ motorcycleId, variant, isAdmin }: Readonly<{ motorcycleId: string; variant?: Tables<"motorcycle_variants">; isAdmin: boolean }>) {
  return <div className="space-y-5"><AdminForm action={saveVariant} submitLabel={variant ? "Update variant" : "Add variant"}><input type="hidden" name="motorcycleId" value={motorcycleId} />{variant ? <input type="hidden" name="id" value={variant.id} /> : null}
    <div className="grid gap-4 sm:grid-cols-3"><label className={adminLabelClass}>Engine CC<input className={adminInputClass} name="cc" type="number" min={25} max={2500} required defaultValue={variant?.cc ?? 150} /></label><label className={adminLabelClass}>Color name<input className={adminInputClass} name="colorName" required minLength={2} maxLength={80} defaultValue={variant?.color_name} /></label><label className={adminLabelClass}>Color HEX<input className={adminInputClass} name="colorHex" type="color" required defaultValue={variant?.color_hex ?? "#000000"} /></label></div>
    <div className="grid gap-4 sm:grid-cols-3"><label className={adminLabelClass}>Price (PKR)<input className={adminInputClass} name="price" type="number" min={0} step="0.01" required defaultValue={variant?.price ?? 0} /></label><label className={adminLabelClass}>Quantity<input className={adminInputClass} name="quantity" type="number" min={0} required defaultValue={variant?.quantity ?? 0} /></label><label className={adminLabelClass}>Stock status<select className={adminInputClass} name="stockStatus" defaultValue={variant?.stock_status ?? "out_of_stock"}><option value="in_stock">In stock</option><option value="out_of_stock">Out of stock</option><option value="coming_soon">Coming soon</option><option value="discontinued">Discontinued</option></select></label></div>
    <div className="flex flex-wrap gap-5"><label className="flex min-h-11 items-center gap-3 text-sm font-semibold"><input type="checkbox" name="isDefault" defaultChecked={variant?.is_default ?? false} className="h-4 w-4 accent-brand" /> Default variant</label><label className="flex min-h-11 items-center gap-3 text-sm font-semibold"><input type="checkbox" name="isActive" defaultChecked={variant?.is_active ?? true} className="h-4 w-4 accent-brand" /> Active variant</label></div>
  </AdminForm>{variant && isAdmin ? <AdminForm action={deleteVariant} submitLabel="Delete variant" pendingLabel="Deleting…" destructive confirmMessage={`Delete the ${variant.cc}cc ${variant.color_name} variant? Related images or specifications may prevent deletion.`} className="border-t border-border pt-5"><input type="hidden" name="id" value={variant.id} /><input type="hidden" name="motorcycleId" value={motorcycleId} /></AdminForm> : null}</div>;
}

export function VariantManager({ motorcycleId, variants, isAdmin }: Readonly<{ motorcycleId: string; variants: readonly Tables<"motorcycle_variants">[]; isAdmin: boolean }>) {
  return <div className="space-y-6"><div className="border border-border bg-soft-gray p-5"><h3 className="font-display text-xl font-bold">Add variant</h3><div className="mt-5"><VariantForm motorcycleId={motorcycleId} isAdmin={isAdmin} /></div></div>{variants.map((variant) => <details key={variant.id} className="group border border-border"><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between gap-4 px-4 [&::-webkit-details-marker]:hidden"><strong>{variant.cc}cc · {variant.color_name}</strong><span className="flex items-center gap-2"><StatusBadge value={variant.stock_status} />{variant.is_default ? <span className="text-[10px] font-bold uppercase text-brand">Default</span> : null}<span aria-hidden="true" className="group-open:rotate-45">＋</span></span></summary><div className="border-t border-border p-5"><VariantForm motorcycleId={motorcycleId} variant={variant} isAdmin={isAdmin} /></div></details>)}</div>;
}
