import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CatalogLayout } from "@/components/catalog/catalog-layout";
import { parseCatalogFilters, type RawSearchParams } from "@/lib/catalog/filters";
import { getCatalogPageData, getPublicBrandBySlug } from "@/lib/supabase/public-queries";
import { catalogMetadataPolicy, createNotFoundMetadata, createPageMetadata } from "@/lib/seo/metadata";
type Props = { params: Promise<{ brand: string }>; searchParams: Promise<RawSearchParams> };
export async function generateMetadata({ params, searchParams }: Props): Promise<Metadata> { const [{ brand }, query] = await Promise.all([params, searchParams]); const item = await getPublicBrandBySlug(brand); if (!item) return createNotFoundMetadata(); const filters = parseCatalogFilters(query); const catalog = await getCatalogPageData(filters, brand); const basePath = `/motorcycles/brand/${brand}`; const policy = catalogMetadataPolicy(query, basePath); const invalidPage = filters.page > catalog.totalPages; return createPageMetadata({ title: item.seoTitle ?? `${item.name} Motorcycles`, description: item.seoDescription ?? `Explore ${item.name} motorcycles at OW Motors.`, path: invalidPage ? basePath : policy.canonicalPath, noIndex: policy.noIndex || invalidPage || catalog.total === 0, absoluteTitle: Boolean(item.seoTitle), ...(item.heroImage ? { image: { src: item.heroImage, alt: `${item.name} motorcycles` } } : {}) }); }
export default async function BrandPage({ params, searchParams }: Props) { const { brand } = await params; const item = await getPublicBrandBySlug(brand); if (!item) notFound(); const filters = parseCatalogFilters(await searchParams); const catalog = await getCatalogPageData(filters, brand); const path = `/motorcycles/brand/${brand}`; return <CatalogLayout title={`${item.name} Motorcycles`} description={item.shortDescription} pathname={path} filters={filters} catalog={catalog} lockedBrand={brand} breadcrumbs={[{ label: "Home", href: "/" }, { label: "Motorcycles", href: "/motorcycles" }, { label: item.name }]} />; }
