import { Search } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { AdminEmptyState, AdminPageHeader, StatusBadge, adminInputClass } from "@/components/admin/admin-ui";
import { getAdminMotorcycleInventory } from "@/lib/admin/queries";
import { motorcycleStoragePublicUrl } from "@/lib/supabase/storage";

function value(input: string | string[] | undefined) { return Array.isArray(input) ? input[0] ?? "" : input ?? ""; }

export default async function InventoryStockPage({ searchParams }: { searchParams: Promise<{ q?: string | string[]; status?: string | string[] }> }) {
  const [query, motorcycles] = await Promise.all([searchParams, getAdminMotorcycleInventory()]);
  const q = value(query.q).trim().toLowerCase();
  const status = value(query.status);
  const rows = motorcycles.flatMap((motorcycle) => motorcycle.variants.map((variant) => ({ motorcycle, variant }))).filter(({ motorcycle, variant }) => {
    const text = `${motorcycle.name} ${motorcycle.brand?.name ?? ""} ${variant.cc} ${variant.color_name}`.toLowerCase();
    return (!q || text.includes(q)) && (!status || variant.stock_status === status);
  });
  return <>
    <AdminPageHeader eyebrow="Inventory" title="Stock & Pricing" description="Review every valid CC and color combination without opening database-oriented records." />
    <section className="mb-6 rounded-lg border border-[#E5E7EB] bg-white p-4"><form action="/admin/inventory/stock" method="get" className="grid gap-3 sm:grid-cols-[minmax(260px,1fr)_200px_auto_auto]"><label className="relative"><span className="sr-only">Search stock</span><Search aria-hidden="true" className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#6B7280]" /><input name="q" defaultValue={value(query.q)} className={`${adminInputClass} mt-0 pl-10`} placeholder="Search motorcycle, brand, CC, or color" /></label><label><span className="sr-only">Stock status</span><select name="status" defaultValue={status} className={`${adminInputClass} mt-0`}><option value="">All stock states</option><option value="in_stock">In stock</option><option value="out_of_stock">Out of stock</option><option value="coming_soon">Coming soon</option><option value="discontinued">Discontinued</option></select></label><button className="min-h-11 rounded-md bg-[#111111] px-4 text-sm font-semibold text-white hover:bg-[#C62828]">Apply filters</button><Link href="/admin/inventory/stock" className="inline-flex min-h-11 items-center justify-center px-3 text-sm font-semibold text-[#C62828] hover:underline">Clear</Link></form></section>
    <div className="mb-3"><p className="text-sm font-bold">{rows.length} stock combination{rows.length === 1 ? "" : "s"}</p><p className="mt-1 text-xs text-[#6B7280]">Edit a product’s Variants section to change quantity, price, or availability.</p></div>
    {rows.length ? <div className="overflow-hidden rounded-lg border border-[#E5E7EB] bg-white"><div className="hidden grid-cols-[minmax(280px,1.6fr)_130px_130px_140px_120px] gap-4 border-b border-[#E5E7EB] bg-[#F7F7F8] px-5 py-3 text-[11px] font-bold uppercase tracking-[0.12em] text-[#6B7280] lg:grid"><span>Motorcycle</span><span>Combination</span><span>Price</span><span>Availability</span><span className="text-right">Action</span></div><div className="divide-y divide-[#E5E7EB]">{rows.map(({ motorcycle, variant }) => { const image = motorcycle.images.find((item) => item.variant_id === variant.id) ?? motorcycle.images[0]; return <article key={variant.id} className="grid gap-4 px-5 py-4 hover:bg-[#F9FAFB] lg:grid-cols-[minmax(280px,1.6fr)_130px_130px_140px_120px] lg:items-center"><div className="flex items-center gap-4"><div className="relative h-14 w-20 shrink-0 overflow-hidden rounded-md border border-[#E5E7EB] bg-[#F7F7F8]">{image ? <Image src={motorcycleStoragePublicUrl(image.storage_path)} alt={image.alt_text} fill sizes="80px" className="object-contain p-1" /> : null}</div><div><strong className="font-display text-lg">{motorcycle.name}</strong><span className="mt-1 block text-xs text-[#6B7280]">{motorcycle.brand?.name ?? "Brand unavailable"}</span></div></div><div><span className="block text-[10px] font-bold uppercase tracking-wide text-[#9CA3AF] lg:hidden">Combination</span><span className="text-sm font-semibold">{variant.cc}cc · {variant.color_name}</span></div><div><span className="block text-[10px] font-bold uppercase tracking-wide text-[#9CA3AF] lg:hidden">Price</span><span className="text-sm font-semibold">PKR {Number(variant.price).toLocaleString("en-PK")}</span></div><div><StatusBadge value={variant.stock_status} /><span className="ml-2 text-xs text-[#6B7280]">Qty {variant.quantity}</span></div><div className="lg:text-right"><Link href={`/admin/inventory/motorcycles/${motorcycle.id}?tab=variants`} className="inline-flex min-h-11 items-center font-semibold text-[#C62828] hover:underline">Edit variant</Link></div></article>; })}</div></div> : <AdminEmptyState title="No stock combinations found" description="Change the filters or add a valid CC and color combination in a motorcycle’s Variants section." />}
  </>;
}
