import { Eye, Plus, Search } from "lucide-react";
import Link from "next/link";
import { AdminEmptyState, AdminPageHeader, StatusBadge, adminInputClass } from "@/components/admin/admin-ui";
import { getAdminBlogCategories, getAdminBlogPosts } from "@/lib/blog/queries";

type Params = { q?: string | string[]; status?: string | string[]; category?: string | string[] };
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] ?? "" : value ?? "";

export default async function AdminBlogPage({ searchParams }: Readonly<{ searchParams: Promise<Params> }>) {
  const [params, posts, categories] = await Promise.all([searchParams, getAdminBlogPosts(), getAdminBlogCategories()]);
  const q = first(params.q).trim().toLowerCase();
  const status = first(params.status);
  const category = first(params.category);
  const filtered = posts.filter((post) => (!q || `${post.title} ${post.author_name} ${post.slug}`.toLowerCase().includes(q)) && (!status || post.publication_status === status) && (!category || post.category?.slug === category));
  return <>
    <AdminPageHeader eyebrow="Inventory" title="Blog" description="Create, review, and publish the stories shown on the OW Motors blog. Draft articles never appear publicly." actions={<Link href="/admin/inventory/blog/new" className="ow-button-primary"><Plus aria-hidden="true" className="h-4 w-4" />New article</Link>} />
    <section className="mb-6 rounded-lg border border-[#E5E7EB] bg-white p-4"><form action="/admin/inventory/blog" method="get" className="grid gap-3 md:grid-cols-[minmax(220px,1fr)_180px_180px_auto]"><label className="relative"><span className="sr-only">Search articles</span><Search aria-hidden="true" className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#6B7280]" /><input name="q" defaultValue={first(params.q)} placeholder="Search title or author" className={`${adminInputClass} mt-0 pl-10`} /></label><select name="status" defaultValue={status} className={`${adminInputClass} mt-0`} aria-label="Publication status"><option value="">All statuses</option><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select><select name="category" defaultValue={category} className={`${adminInputClass} mt-0`} aria-label="Article category"><option value="">All categories</option>{categories.map((item) => <option key={item.id} value={item.slug}>{item.name}</option>)}</select><button className="min-h-11 rounded-md bg-[#111111] px-4 text-sm font-semibold text-white transition-colors hover:bg-[#C62828]">Apply</button></form></section>
    {filtered.length ? <div className="overflow-hidden rounded-lg border border-[#E5E7EB] bg-white"><div className="hidden grid-cols-[minmax(300px,2fr)_160px_130px_130px] gap-4 border-b border-[#E5E7EB] bg-[#F7F7F8] px-5 py-3 text-[11px] font-bold uppercase tracking-[0.12em] text-[#6B7280] lg:grid"><span>Article</span><span>Category</span><span>Status</span><span className="text-right">Actions</span></div><div className="divide-y divide-[#E5E7EB]">{filtered.map((post) => <article key={post.id} className="grid gap-4 px-5 py-4 hover:bg-[#F9FAFB] lg:grid-cols-[minmax(300px,2fr)_160px_130px_130px] lg:items-center"><div><h2 className="font-display text-xl font-bold leading-tight text-[#111111]">{post.title}</h2><p className="mt-1 text-xs text-[#6B7280]">{post.author_name} · {post.reading_time_minutes} min read{post.is_featured ? " · Featured" : ""}</p></div><div className="text-sm font-semibold text-[#374151]">{post.category?.name ?? "Unassigned"}</div><div><StatusBadge value={post.publication_status} /></div><div className="flex items-center justify-end gap-1"><Link href={`/admin/inventory/blog/${post.id}`} className="inline-flex min-h-11 items-center px-2 text-sm font-bold !text-[#C62828] hover:underline">Edit</Link>{post.publication_status === "published" ? <Link href={`/blog/${post.slug}`} target="_blank" rel="noreferrer" aria-label={`Preview ${post.title}`} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-md text-[#6B7280] hover:bg-[#FEF2F2] hover:text-[#C62828]"><Eye aria-hidden="true" className="h-4 w-4" /></Link> : null}</div></article>)}</div></div> : <AdminEmptyState title="No articles in this view" description="Clear the filters or create a new OW Motors article draft." action={<Link href="/admin/inventory/blog/new" className="ow-button-primary">New article</Link>} />}
  </>;
}

